### ISSUE TITLE
Incompatible type conversion in GameStatsServiceImpl

### ISSUE THREAD

**Issue by XaeroDegreaz** [djr4488/cards#1]
What sorcery do you use to get [this line of code](https://github.com/djr4488/cards/blob/master/src/main/java/com/djr/cards/games/stats/service/GameStatsServiceImpl.java#L92) to compile?

`List<Game>` implicit cast to `List<String>`? Madness! I see you've overridden `toString()` in the `Game` class, but I'm still missing how you're getting that line to compile. Both Eclipse, and IntelliJ crumble there.

**Comment by djr4488** [comment]
It is possible I checked that in before compiling it.  Since the computer I
use to do the work on at the moment cannot connect to the internet I need
to check it out and fix it I suppose. :D

On Thu, May 22, 2014 at 12:17 PM, Jerome Doby notifications@github.comwrote:

> What sorcery do you use to get this line of codehttps://github.com/djr4488/cards/blob/master/src/main/java/com/djr/cards/games/stats/service/GameStatsServiceImpl.java#L92to compile?
> 
> List<Game> implicit cast to List<String>? Madness! I see you've
> overridden toString() in the Game class, but I'm still missing how you're
> getting that line to compile. Both Eclipse, and IntelliJ crumble there.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/djr4488/cards/issues/1
> .

## 

Daniel Rucker

Where's the kaboom?  There's supposed to be an Earth shattering kaboom! -
Marvin the Martian

**Comment by djr4488** [comment]
(I was actually in process of changing it from List<String> to List<Game>

On Thu, May 22, 2014 at 1:04 PM, Danny Rucker rucker.danny@gmail.comwrote:

> It is possible I checked that in before compiling it.  Since the computer
> I use to do the work on at the moment cannot connect to the internet I need
> to check it out and fix it I suppose. :D
> 
> On Thu, May 22, 2014 at 12:17 PM, Jerome Doby notifications@github.comwrote:
> 
> > What sorcery do you use to get this line of codehttps://github.com/djr4488/cards/blob/master/src/main/java/com/djr/cards/games/stats/service/GameStatsServiceImpl.java#L92to compile?
> > 
> > List<Game> implicit cast to List<String>? Madness! I see you've
> > overridden toString() in the Game class, but I'm still missing how
> > you're getting that line to compile. Both Eclipse, and IntelliJ crumble
> > there.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/djr4488/cards/issues/1
> > .
> 
> ## 
> 
> Daniel Rucker
> 
> Where's the kaboom?  There's supposed to be an Earth shattering kaboom! -
> Marvin the Martian

## 

Daniel Rucker

Where's the kaboom?  There's supposed to be an Earth shattering kaboom! -
Marvin the Martian

**Comment by XaeroDegreaz** [comment]
Want a pull request? ;)

**Comment by djr4488** [comment]
Sure.

On Thu, May 22, 2014 at 1:06 PM, Jerome Doby notifications@github.comwrote:

> Want a pull request? ;)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/djr4488/cards/issues/1#issuecomment-43923235
> .

## 

Daniel Rucker

Where's the kaboom?  There's supposed to be an Earth shattering kaboom! -
Marvin the Martian
